// Code generated by protoc-gen-go. DO NOT EDIT.
// source: convention/protobuf/TcpProtocol结构体的副本.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TTTT struct {
	Ssss                 string   `protobuf:"bytes,1,opt,name=ssss,proto3" json:"ssss,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TTTT) Reset()         { *m = TTTT{} }
func (m *TTTT) String() string { return proto.CompactTextString(m) }
func (*TTTT) ProtoMessage()    {}
func (*TTTT) Descriptor() ([]byte, []int) {
	return fileDescriptor_44f0a7e7f0c74424, []int{0}
}

func (m *TTTT) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TTTT.Unmarshal(m, b)
}
func (m *TTTT) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TTTT.Marshal(b, m, deterministic)
}
func (m *TTTT) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TTTT.Merge(m, src)
}
func (m *TTTT) XXX_Size() int {
	return xxx_messageInfo_TTTT.Size(m)
}
func (m *TTTT) XXX_DiscardUnknown() {
	xxx_messageInfo_TTTT.DiscardUnknown(m)
}

var xxx_messageInfo_TTTT proto.InternalMessageInfo

func (m *TTTT) GetSsss() string {
	if m != nil {
		return m.Ssss
	}
	return ""
}

func init() {
	proto.RegisterType((*TTTT)(nil), "protocol.TTTT")
}

func init() {
	proto.RegisterFile("convention/protobuf/TcpProtocol结构体的副本.proto", fileDescriptor_44f0a7e7f0c74424)
}

var fileDescriptor_44f0a7e7f0c74424 = []byte{
	// 112 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x32, 0x4f, 0xce, 0xcf, 0x2b,
	0x4b, 0xcd, 0x2b, 0xc9, 0xcc, 0xcf, 0xd3, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0x4f, 0x2a, 0x4d, 0xd3,
	0x0f, 0x49, 0x2e, 0x08, 0x00, 0xb1, 0x93, 0xf3, 0x73, 0x9e, 0xef, 0x9e, 0xfc, 0x6c, 0x5e, 0xcb,
	0x93, 0xbd, 0x93, 0x9f, 0xcf, 0x6a, 0x79, 0xda, 0xb9, 0xfe, 0xd9, 0x9c, 0x35, 0x7a, 0x60, 0x65,
	0x42, 0x1c, 0x05, 0x50, 0x15, 0x4a, 0x52, 0x5c, 0x2c, 0x21, 0x21, 0x21, 0x21, 0x42, 0x42, 0x5c,
	0x2c, 0xc5, 0xc5, 0xc5, 0xc5, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x60, 0x76, 0x12, 0x1b,
	0x58, 0x95, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x80, 0xb1, 0x6e, 0xb5, 0x67, 0x00, 0x00, 0x00,
}
