// Code generated by protoc-gen-go. DO NOT EDIT.
// source: convention/protobuf/GoPass通讯协议请求头.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GoPassRequestHead struct {
	BodyLen              uint32   `protobuf:"varint,1,opt,name=bodyLen,proto3" json:"bodyLen,omitempty"`
	LangType             string   `protobuf:"bytes,2,opt,name=langType,proto3" json:"langType,omitempty"`
	Date                 string   `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GoPassRequestHead) Reset()         { *m = GoPassRequestHead{} }
func (m *GoPassRequestHead) String() string { return proto.CompactTextString(m) }
func (*GoPassRequestHead) ProtoMessage()    {}
func (*GoPassRequestHead) Descriptor() ([]byte, []int) {
	return fileDescriptor_df8f91e0ed75a453, []int{0}
}

func (m *GoPassRequestHead) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GoPassRequestHead.Unmarshal(m, b)
}
func (m *GoPassRequestHead) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GoPassRequestHead.Marshal(b, m, deterministic)
}
func (m *GoPassRequestHead) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GoPassRequestHead.Merge(m, src)
}
func (m *GoPassRequestHead) XXX_Size() int {
	return xxx_messageInfo_GoPassRequestHead.Size(m)
}
func (m *GoPassRequestHead) XXX_DiscardUnknown() {
	xxx_messageInfo_GoPassRequestHead.DiscardUnknown(m)
}

var xxx_messageInfo_GoPassRequestHead proto.InternalMessageInfo

func (m *GoPassRequestHead) GetBodyLen() uint32 {
	if m != nil {
		return m.BodyLen
	}
	return 0
}

func (m *GoPassRequestHead) GetLangType() string {
	if m != nil {
		return m.LangType
	}
	return ""
}

func (m *GoPassRequestHead) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func init() {
	proto.RegisterType((*GoPassRequestHead)(nil), "protocol.GoPassRequestHead")
}

func init() {
	proto.RegisterFile("convention/protobuf/GoPass通讯协议请求头.proto", fileDescriptor_df8f91e0ed75a453)
}

var fileDescriptor_df8f91e0ed75a453 = []byte{
	// 161 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x32, 0x4d, 0xce, 0xcf, 0x2b,
	0x4b, 0xcd, 0x2b, 0xc9, 0xcc, 0xcf, 0xd3, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0x4f, 0x2a, 0x4d, 0xd3,
	0x77, 0xcf, 0xf7, 0xc9, 0x4f, 0xce, 0x7e, 0xd9, 0x30, 0xeb, 0xc5, 0xba, 0xf5, 0x4f, 0x7b, 0xfb,
	0x5f, 0xac, 0x5b, 0xf7, 0x62, 0xfd, 0xf6, 0x67, 0x1b, 0x9b, 0x9e, 0x2e, 0xd9, 0xa2, 0x07, 0x56,
	0x24, 0xc4, 0x01, 0xa6, 0x92, 0xf3, 0x73, 0x94, 0x62, 0xb9, 0x04, 0x21, 0xca, 0x83, 0x52, 0x0b,
	0x4b, 0x53, 0x8b, 0x4b, 0x3c, 0x52, 0x13, 0x53, 0x84, 0x24, 0xb8, 0xd8, 0x93, 0xf2, 0x53, 0x2a,
	0x7d, 0x52, 0xf3, 0x24, 0x18, 0x15, 0x18, 0x35, 0x78, 0x83, 0x60, 0x5c, 0x21, 0x29, 0x2e, 0x8e,
	0x9c, 0xc4, 0xbc, 0xf4, 0x90, 0xca, 0x82, 0x54, 0x09, 0x26, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x38,
	0x5f, 0x48, 0x88, 0x8b, 0x25, 0x25, 0xb1, 0x24, 0x55, 0x82, 0x19, 0x2c, 0x0e, 0x66, 0x27, 0xb1,
	0x81, 0x2d, 0x32, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xd5, 0xc5, 0x58, 0x4b, 0xa8, 0x00, 0x00,
	0x00,
}
